# Generated by Django 4.0.4 on 2022-05-13 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_stock_available_and_more'),
        ('cart', '0002_alter_item_product_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('cart_id', 'product_id')},
        ),
    ]
