# Generated by Django 4.0.4 on 2022-05-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField()),
                ('price_ht', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock_available', models.IntegerField(default=0)),
                ('stock_ordered', models.IntegerField(default=0)),
                ('tva', models.DecimalField(choices=[('5,5%', 5.5), ('20%', '20.00')], decimal_places=2, default='5,5%', max_digits=4)),
            ],
        ),
    ]
