# Generated by Django 4.0.4 on 2022-05-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='tva',
            field=models.DecimalField(choices=[(5.5, '5,5%'), (20.0, '20%')], decimal_places=2, default='5,5%', max_digits=4),
        ),
    ]
